# Generated by Django 3.1 on 2020-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioss', '0002_suscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
