# Generated by Django 3.1.5 on 2021-08-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioss', '0003_auto_20201111_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='suscribers',
            new_name='Suscriber',
        ),
    ]
