# Generated by Django 3.1.5 on 2021-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioss', '0005_auto_20210825_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriber',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
